header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - '**/*.md'
    - 'LICENSE'
    - '**/testdata/**'

  comment: on-failure

dependency:
  files:
    - go.mod
