header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: ripls56

  paths-ignore:
    - '**/*.md'
    - 'LICENSE'
    - 'go.sum'
    - '**/testdata/**'

  comment: on-failure

dependency:
  files:
    - go.mod
