on:
  push:
    branches:
      - main

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@v0.6.0
      - name: Fix License Header
        uses: apache/skywalking-eyes/header@v0.6.0
        with:
            mode: fix
      - name: Apply Changes
        uses: EndBug/add-and-commit@v9.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'
