on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@0.6.0
            config: .licenserc.yaml
      - name: Fix License Header
        uses: apache/skywalking-eyes/header@0.6.0
          with:
            mode: fix
      - name: Apply Changes
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'
