on:
  push:
    branches:
      - main
      
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@v0.6.0
      - name: Fix License Header
        uses: apache/skywalking-eyes/header@v0.6.0
        with:
            mode: fix
      - name: Create pull request with changes
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Fix: Automatic application of license header'
          branch: license-fix
          title: 'Fix License Headers'
          body: |
            This pull request applies automatic fixes to license headers.
          labels: license, automation
